version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      # Add this line to prevent overwriting Python modules
      - /app/venv
    environment:
      - DATABASE_URL=mongodb://mongo:27017/realestate
      - API_KEY_ZILLOW=${API_KEY_ZILLOW}
      - API_KEY_REALTOR=${API_KEY_REALTOR}
      - MLS_USERNAME=${MLS_USERNAME}
      - MLS_PASSWORD=${MLS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: unless-stopped
  